os:
  editPreset: vscode
gui:
  theme:
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
  showIcons: true
  mouseEvents: false
paging:
  colorArg: always
  pager: delta
